### ISSUE TITLE
[Server thread/WARN]: Missing metadata in pack file/RestartRedstone-main.zip

### ISSUE THREAD

**Issue by boopidoop** [hermitcraft-official/RestartRedstone#2]
Whenever the data pack is loaded, the warning "[Server thread/WARN]: Missing metadata in pack file/RestartRedstone-main.zip" is shown in the server console. 
Also, when entering "datapack list" into the console, the data pack isn't listed under "There are [x] data pack(s) enabled:" or "There are [x] data pack(s) available:".
Both issues appear to be fixed if you extract the downloaded .zip file contents, as the file contains a folder containing the data pack. I believe this is just how GitHub handles downloaded files, would recommend updating the instructions to say "To use this datapack, click on the green "Code" button in the top right, choose "Download Zip" and extract the contents of the zip file into your world's datapacks folder." or similar.

Screenshot of the console output for my server, showing loaded data packs and the warning message mentioned in the title. Enabled data packs are listed in alphabetical order, but "file/RestartRedstone-main (world)" is missing.
![image](https://github.com/user-attachments/assets/bbb3b601-e724-4805-9d11-61296251d94c)

Screenshots of the downloaded .zip file, showing the folder inside, and the contents of the folder.
![image](https://github.com/user-attachments/assets/04b3aca4-9318-47a5-98b0-8a633ea55231)
![image](https://github.com/user-attachments/assets/136fd5db-c7da-4c90-9492-7cb0589c12b0)

**Comment by boopidoop** [comment]
Made this as a separate issue as the other issue (#1) doesn't have the specific warning in the title

**Comment by Plagiatus** [comment]
Turns out the install instructions in the README were wrong. You need to unzip the file inside the datapacks folder to work.

I'll close the issue now, please reopen it if it still doesn't work.
